package com.esmc.mcnp.model.security;

// Generated 19 oct. 2014 00:49:35 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "eu_user")
public class EuUser implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private int idUser;
	private String login;
	private String hashedPassword;
	private boolean actif;
	private boolean pwdChFlag;
	private Date dateCreation;
	private Integer dureeValidite;
	private boolean expired;
	private Date dateExpiration;
	private Date lastLoginDate;
	private EuUtilisateur euUtilisateur;
	private Set<EuUserRole> roleUtilisateurs = new HashSet<EuUserRole>();

	public EuUser() {
	}
	
	public EuUser(String login, String hashedPassword, boolean actif, boolean pwdChFlag, Date dateCreation,
			boolean expired) {
		this.login = login;
		this.hashedPassword = hashedPassword;
		this.actif = actif;
		this.pwdChFlag = pwdChFlag;
		this.dateCreation = dateCreation;
		this.expired = expired;
	}

	public EuUser(int idUser, String login, String hashedPassword, boolean actif, boolean pwdChFlag, Date dateCreation,
			boolean expired) {
		this.idUser = idUser;
		this.login = login;
		this.hashedPassword = hashedPassword;
		this.actif = actif;
		this.pwdChFlag = pwdChFlag;
		this.dateCreation = dateCreation;
		this.expired = expired;
	}

	public EuUser(int idUser, String login, String hashedPassword, boolean actif, boolean pwdChFlag, Date dateCreation,
			Integer dureeValidite, boolean expired, Date dateExpiration, Date lastLoginDate,
			Set<EuUserRole> roleUtilisateurs) {
		this.idUser = idUser;
		this.login = login;
		this.hashedPassword = hashedPassword;
		this.actif = actif;
		this.pwdChFlag = pwdChFlag;
		this.dateCreation = dateCreation;
		this.dureeValidite = dureeValidite;
		this.expired = expired;
		this.dateExpiration = dateExpiration;
		this.lastLoginDate = lastLoginDate;
		this.roleUtilisateurs = roleUtilisateurs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_user", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "login", nullable = false, length = 30)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Basic(fetch = FetchType.LAZY)
	@Column(name = "password")
	public String getHashedPassword() {
		return this.hashedPassword;
	}

	public void setHashedPassword(String password) {
		this.hashedPassword = password;
	}

	@Column(name = "actif", nullable = false)
	public boolean isActif() {
		return this.actif;
	}

	public void setActif(boolean actif) {
		this.actif = actif;
	}

	@Column(name = "pwd_ch_flag", nullable = false)
	public boolean isPwdChFlag() {
		return this.pwdChFlag;
	}

	public void setPwdChFlag(boolean pwdChFlag) {
		this.pwdChFlag = pwdChFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_creation", nullable = false, length = 13)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "duree_validite")
	public Integer getDureeValidite() {
		return this.dureeValidite;
	}

	public void setDureeValidite(Integer dureeValidite) {
		this.dureeValidite = dureeValidite;
	}

	@Column(name = "expired", nullable = false)
	public boolean isExpired() {
		return this.expired;
	}

	public void setExpired(boolean expired) {
		this.expired = expired;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_expiration", length = 13)
	public Date getDateExpiration() {
		return this.dateExpiration;
	}

	public void setDateExpiration(Date dateExpiration) {
		this.dateExpiration = dateExpiration;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_login_date", length = 13)
	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	@OneToOne
	@JoinColumn(name = "id_utilisateur")
	public EuUtilisateur getEuUtilisateur() {
		return euUtilisateur;
	}

	public void setEuUtilisateur(EuUtilisateur euUtilisateur) {
		this.euUtilisateur = euUtilisateur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "euUser")
	public Set<EuUserRole> getRoleUtilisateurs() {
		return roleUtilisateurs;
	}

	public void setRoleUtilisateurs(Set<EuUserRole> roleUtilisateurs) {
		this.roleUtilisateurs = roleUtilisateurs;
	}

}
